

services:
  backend:
    build:
      context: ./backend
    container_name: kidshield-backend
    env_file:
      - ./backend/.env
    ports:
      - "4000:4000"
    networks:
      - kidshield-net

  admin:
    build:
      context: ./admin
    container_name: kidshield-admin
    ports:
      - "5174:5174"
    networks:
      - kidshield-net

  frontend:
    build:
      context: ./frontend 
    container_name: kidshield-frontend
    ports:
      - "5173:5173"
    networks:
      - kidshield-net

networks:
  kidshield-net:
    driver: bridge
