name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'

      # Install and build Backend
      - name: Install and Build Backend
        working-directory: backend
        run: |
          npm install
          npm run build

      # Install and build Frontend
      - name: Install and Build Frontend
        working-directory: frontend
        run: |
          npm install
          npm run build

      # Admin build step is skipped because it has no package.json
